# Generated by Django 3.2.16 on 2022-11-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teaches_courses',
            field=models.ManyToManyField(blank=True, to='report.Course'),
        ),
    ]
