# Generated by Django 2.2.19 on 2022-11-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(default=1, max_length=30, verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
