# Generated by Django 3.2.16 on 2022-11-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='grade_1',
            field=models.IntegerField(choices=[('', 'null'), (2, 2), (3, 3), (4, 4), (5, 5)], default='', null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade_10',
            field=models.IntegerField(choices=[('', 'null'), (2, 2), (3, 3), (4, 4), (5, 5)], default='', null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade_11',
            field=models.IntegerField(choices=[('', 'null'), (2, 2), (3, 3), (4, 4), (5, 5)], default='', null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade_12',
            field=models.IntegerField(choices=[('', 'null'), (2, 2), (3, 3), (4, 4), (5, 5)], default='', null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade_13',
            field=models.IntegerField(choices=[('', 'null'), (2, 2), (3, 3), (4, 4), (5, 5)], default='', null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade_14',
            field=models.IntegerField(choices=[('', 'null'), (2, 2), (3, 3), (4, 4), (5, 5)], default='', null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade_15',
            field=models.IntegerField(choices=[('', 'null'), (2, 2), (3, 3), (4, 4), (5, 5)], default='', null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade_16',
            field=models.IntegerField(choices=[('', 'null'), (2, 2), (3, 3), (4, 4), (5, 5)], default='', null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade_2',
            field=models.IntegerField(choices=[('', 'null'), (2, 2), (3, 3), (4, 4), (5, 5)], default='', null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade_3',
            field=models.IntegerField(choices=[('', 'null'), (2, 2), (3, 3), (4, 4), (5, 5)], default='', null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade_4',
            field=models.IntegerField(choices=[('', 'null'), (2, 2), (3, 3), (4, 4), (5, 5)], default='', null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade_5',
            field=models.IntegerField(choices=[('', 'null'), (2, 2), (3, 3), (4, 4), (5, 5)], default='', null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade_6',
            field=models.IntegerField(choices=[('', 'null'), (2, 2), (3, 3), (4, 4), (5, 5)], default='', null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade_7',
            field=models.IntegerField(choices=[('', 'null'), (2, 2), (3, 3), (4, 4), (5, 5)], default='', null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade_8',
            field=models.IntegerField(choices=[('', 'null'), (2, 2), (3, 3), (4, 4), (5, 5)], default='', null=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade_9',
            field=models.IntegerField(choices=[('', 'null'), (2, 2), (3, 3), (4, 4), (5, 5)], default='', null=True),
        ),
    ]
