# Generated by Django 3.2.16 on 2022-11-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_user_teaches_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teaches_courses',
            field=models.ManyToManyField(blank=True, related_name='coursess', to='report.Course'),
        ),
    ]
