# Generated by Django 3.2.16 on 2022-11-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20221121_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='visit_1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='visit_10',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='visit_11',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='visit_12',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='visit_13',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='visit_14',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='visit_15',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='visit_16',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='visit_2',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='visit_3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='visit_4',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='visit_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='visit_6',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='visit_7',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='visit_8',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='visit_9',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
