# Generated by Django 3.2.16 on 2022-11-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20221121_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Студент', 'Студент'), ('Преподаватель', 'Преподаватель'), ('Администратор', 'Администратор')], default='Студент', max_length=30, verbose_name='Роль'),
        ),
    ]
