# Generated by Django 3.2.16 on 2022-11-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teaches_courses',
            field=models.ManyToManyField(blank=True, null=True, to='report.Course'),
        ),
    ]
